### PR TITLE
Added JPMorgan

### PR DESCRIPTION
**Pull request by xamat**

### CODE REVIEW

**Comment by duffn** [comment]
Thanks for the contribution! Do you have a screenshot to add as well?

**Comment by xamat** [comment]
I do. I was just unsure I should just upload to the screenshot folder

**Comment by duffn** [comment]
Yep! And then one more addition at the bottom of the readme. Example here: https://github.com/duffn/dumb-password-rules/pull/425/files

**Comment by duffn** [comment]
Thanks for your previous submission! 

I've recently migrated the site from a simple README to a full static site (https://github.com/duffn/dumb-password-rules/pull/443).

If you're interested in re-submitting your entry, please create a new PR following the new contributing doc here (https://github.com/duffn/dumb-password-rules/blob/master/CONTRIBUTING.md).

**Pull request closed without merging**
