### PR TITLE
Added Ubisoft

### PR DESCRIPTION
**Pull request by dawnerd**
Ran across this gem while trying to resurrect my old ubisoft account.

Sidenote: Any interest in getting this on GH pages? I'd be happy to donate a domain

### CODE REVIEW

**Comment by duffn** [comment]
Sure, I think getting this in GH pages would be great. 👍

**Comment by JoshuaBehrens** [comment]
What is about the domain thing?

**Comment by duffn** [comment]
I really haven't had time to do much with this, I'm afraid. If anybody has interest in still giving something a try, let me know.

**Comment by JoshuaBehrens** [comment]
Is it about the domain or the gh pages?

**Comment by duffn** [comment]
It’s about building something from the README into the GH pages. The domain was already purchased.

**Pull request merged**
