### PR TITLE
Craigslist's dumb password

### PR DESCRIPTION
**Pull request by MrCyGuy**
Did you know how dumb craigslist's password requirements are?

### CODE REVIEW

**Comment by MrCyGuy** [comment]
Can someone approve my PR?

**Comment by MrCyGuy** [comment]
I need a PR acceptance

**Comment by MrCyGuy** [comment]
Hi, is there anything I have to do get this merged?

**Review by duffn — APPROVED** [review]

**Comment by duffn** [comment]
Thank you for the contribution!

**Pull request merged**
