### PR TITLE
TCF Bank

### PR DESCRIPTION
**Pull request by kazooless**
(https://www.billerpayments.com/app/cust/loginsetup.do>

Rejects any special characters (explicitly tells you they're not allowed after you try). Trying to enter 32 characters with a mix of lower, upper & numerals and it says it is a weak password. Also, can't be sure but when typing manually, it seems it stops at 20 characters.

Just shameful

### CODE REVIEW

**Comment by duffn** [comment]
Thanks for your submission. Can you add a description as with the other entries?

**Comment by kazooless** [comment]
Nicholas,

I thought I added it everywhere I could. I’m not a common GitHub user, so I’m not hugely familiar with it. However, it made me create my own fork. I added the PNG there along with text in the comment. I also added a new page of “code” with that same text along with the same text in that code’s comment.

So, what am I missing? 

Jeff

**Comment by duffn** [comment]
No problem. Almost there. 

You just need to add an entry to the README.md file with a header, short description and a link to the screenshot that you already uploaded. Here's a current example.

```
### [MKB NetBankár](https://www.mkbnetbankar.hu/)

It only accepts lowercase letters, uppercase letters and numbers (any other character counts as forbidden character).  
Also, if your password contains any invalid character, it will get marked as "Identical to the former 10 passwords".

To make it more fun, during the registration, it allows to set a 24 characters password to login to their website.  
Once you try to login with the password, it will say that the maximum length accepted is 16 characters.  
What actually happens, is that they let you insert 24 characters during registration, but only the first 16 will get actually used as password.

![MKB NetBankár](/screenshots/mkb.png "MKB NetBankár")
```

The `###` before the title makes it a headline and the format at the end of the entry like `MKB NetBankár` actually shows your screenshot in the README.

Add your entry in alphabetical order and we should be good to go! (If you commit the same way you did with the screenshot and push back to your fork, it'll automatically show up here).

Don't hesitate to ask if you have any more questions.

**Comment by duffn** [comment]
Thanks for your previous submission! 

I've recently migrated the site from a simple README to a full static site (https://github.com/duffn/dumb-password-rules/pull/443).

If you're interested in re-submitting your entry, please create a new PR following the new contributing doc here (https://github.com/duffn/dumb-password-rules/blob/master/CONTRIBUTING.md).

**Pull request closed without merging**
