### PR TITLE
Added Freepik, aplhabetized the list, fixed some namings and spacing

### PR DESCRIPTION
**Pull request by Laegas**
Added Freepik, aplhabetized the list, fixed some namings and spacing

### CODE REVIEW

**Comment by duffn** [comment]
Thanks! This is a big one, so I’ll take a look soon.

**Comment by Laegas** [comment]
@duffn any update on this? :smile:

**Comment by duffn** [comment]
Hi @Laegas, it looks like we have some merge conflicts if you could fix those first. Thanks.

**Comment by Laegas** [comment]
@duffn Conflicts resolved 😊

**Review by duffn — APPROVED** [review]

**Comment by duffn** [comment]
Thanks!

**Pull request merged**
