### PR TITLE
liberty mutual

### PR DESCRIPTION
**Pull request by depperm**

### CODE REVIEW

**Review by duffn — APPROVED** [review]

**Comment by duffn** [comment]
Thank you for the contribution!

**Comment by depperm** [comment]
@duffn so I checked the homepage and it looks like the image isn't displaying right. Do you see what I entered wrong? I can try to fix it later, or if you see what I did you can

**Comment by duffn** [comment]
@depperm Ah yes, I missed that. You need to add an entry near the end of the file in this format, connecting the `|libertymutual|` line to the actual image.

```
.. |lcl.fr| image:: /screenshots/lcl.png
```

**Comment by depperm** [comment]
@duffn just found that. Sorry wasn't familiar with rst format, will hopefully get to this later today

**Pull request merged**
